clioutput = """tomcat/tomcat.pem: Certificate Signed by HSBC-LAB-CA
ipsec/ipsec.pem: Self-signed certificate generated by system
CallManager/CallManager.pem: Self-signed certificate generated by system
CAPF/CAPF.pem: Self-signed certificate generated by system
TVS/TVS.pem: Self-signed certificate generated by system
ITLRecovery/ITLRecovery.pem: Self-signed certificate generated by system"""


def Strip_certificate_name(clioutput):
    # Function returns the certificates names on the CM in a list 
    string = clioutput.splitlines()
    i =0
    certList = []
    for line in string:
        certList.append(line.split(':')[0])
        i+=1
    return certList

print(Strip_certificate_name(clioutput))

failed_node = ['10.1.1.1','10.20.20.2']
for items in failed_node:
    print(items)
    